services:
  cache:
    image: redis:latest
    container_name: cache_area
    networks:
      - area_network
    command: ["redis-server", "--port", "6380"]
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - cache_data:/data

  server:
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6380
    build:
      context: Backend/
    container_name: server_area
    image: server_area
    depends_on:
      - cache
    ports:
      - "8080:8080"
    networks:
      - area_network

volumes:
  cache_data:
  app_volume:

networks:
  area_network:
    driver: bridge